
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
target 'tctmass' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  target 'tctmassTests' do
    inherit! :complete
    # Pods for testing
  end
   # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec`'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'tctmass-tvOS' do
  # Pods for tctmass-tvOS

  target 'tctmass-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
